load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_test(
    name = "buf",
    size = "small",
    srcs = ["buf.cc"],
    deps = [
        "//a3:buffer",
        "//a3:str",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "str",
    size = "small",
    srcs = ["str.cc"],
    deps = [
        "//a3:str",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "ht",
    size = "small",
    srcs = ["ht.cc"],
    deps = [
        "//a3:ht",
        "//a3:str",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "try",
    size = "small",
    srcs = ["try.cc"],
    deps = [
        "//a3:try",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "log",
    size = "small",
    srcs = ["log.cc"],
    deps = [
        "//a3:log",
        "//a3:str",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "cache",
    size = "small",
    srcs = ["cache.cc"],
    deps = [
        "//a3:cache",
        "//a3:ht",
        "//a3:log",
        "//a3:str",
        "//a3/shim:types",
        "@googletest//:gtest_main",
    ]
)
