module(
    name = "a3",
    version = "0.6.0",
)

bazel_dep(name = "rules_cc", version = "0.2.22")
single_version_override(
    module_name = "rules_cc",
    patch_strip = 1,
    patches = [
        "//bazel:openbsd_origin.patch",
        "//bazel:openbsd_default_libs.patch",
    ],
)

bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "bazel_skylib", version = "1.9.0")

include("//bazel:toolchains.MODULE.bazel")

bazel_dep(name = "hedron_compile_commands", dev_dependency = True)
git_override(
    module_name = "hedron_compile_commands",
    commit = "6c416550b3a4a2aac95b34ca484a936a779445c4",
    # Patches:
    # * https://github.com/hedronvision/bazel-compile-commands-extractor/pull/278
    # * C++ module file extensions.
    # * https://github.com/hedronvision/bazel-compile-commands-extractor/pull/276
    remote = "https://github.com/3541/bazel-compile-commands-extractor.git",
)

bazel_dep(name = "googletest", version = "1.17.0.bcr.2", dev_dependency = True)
