package(default_visibility = ["//visibility:public"])

constraint_setting(name = "compiler")

constraint_value(
    name = "gcc",
    constraint_setting = ":compiler",
)

constraint_value(
    name = "clang",
    constraint_setting = ":compiler",
)

constraint_value(
    name = "msvc",
    constraint_setting = ":compiler",
)

platform(
    name = "host_gcc",
    constraint_values = [":gcc"],
    parents = ["@rules_nixpkgs_core//platforms:host"],
)

platform(
    name = "host_system_gcc",
    constraint_values = [":gcc"],
    parents = ["@local_config_platform//:host"]
)

platform(
    name = "host_clang",
    constraint_values = [":clang"],
    parents = ["@rules_nixpkgs_core//platforms:host"],
)

platform(
    name = "host_system_clang",
    constraint_values = [":clang"],
    parents = ["@local_config_platform//:host"]
)

platform(
    name = "host_system_msvc",
    constraint_values = [":msvc"],
    parents = ["@local_config_platform//:host"]
)

