version: 2.1

jobs:
  build-aarch64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: |
          pip3 install meson
          sudo apt-get install -y ninja-build
      - checkout
      - run:
          name: "Configure"
          command: "meson setup --buildtype debug --werror -Db_sanitize=address,undefined -Dcpp_std=c++20 build"
      - run:
          name: "Build"
          command: "meson compile -C build"
      - run:
          name: "Test"
          command: "meson test -C build"

workflows:
  build-and-test:
    jobs:
      - build-aarch64
