version: 2.1

jobs:
  build-aarch64:
    docker:
      - image: cimg/base:2023.06
    resource_class: arm.medium
    steps:
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install ninja-build gcc-10 g++-10 python3-pip
            sudo pip install meson
      - checkout
      - run:
          name: "Configure"
          command: "CC=gcc-10 CXX=g++-10 ci/configure.sh build"
      - run:
          name: "Build"
          command: "ci/build.sh build"
      - run:
          name: "Test"
          command: "ci/test.sh build"
      - store_test_results:
          path: build/a3_gtest.xml
  build-bazel-aarch64:
    docker:
      - image: cimg/base:2025.12
    resource_class: arm.medium
    steps:
      - checkout
      - restore_cache:
          keys:
            - bazel-bazelisk-{{ checksum ".bazelversion" }}
      - restore_cache:
          keys:
            - bazel-repo-cache-{{ checksum "MODULE.bazel.lock" }}
      - run:
          name: Install dependencies
          command: |
            if [[ ! -f /tmp/bazelisk ]]; then
              sudo curl -L https://github.com/bazelbuild/bazelisk/releases/download/v1.27.0/bazelisk-linux-arm64 -o /tmp/bazelisk
            fi

            sudo cp /tmp/bazelisk /usr/local/bin/bazel
            sudo chmod +x /usr/local/bin/bazel
      - run:
          name: Bazel test
          command: |
            bazel test --config=system-gcc --repository_cache=./repo_cache ...
      - save_cache:
          key: bazel-bazelisk-{{ checksum ".bazelversion" }}
          paths:
            - /tmp/bazelisk
      - save_cache:
          key: bazel-repo-cache-{{ checksum "MODULE.bazel.lock" }}
          paths:
            - repo_cache
      - store_test_results:
          path: bazel-testlogs
  build-bazel-aarch64-darwin:
    macos:
      xcode: 16.4.0
    resource_class: m4pro.medium
    steps:
      - checkout
      - restore_cache:
          keys:
            - bazel-darwin-bazelisk-{{ checksum ".bazelversion" }}
      - restore_cache:
          keys:
            - bazel-darwin-repo-cache-{{ checksum "MODULE.bazel.lock" }}
      - run:
          name: Install dependencies
          command: |
            if [[ ! -f /tmp/bazelisk ]]; then
              sudo curl -L https://github.com/bazelbuild/bazelisk/releases/download/v1.27.0/bazelisk-darwin-arm64 -o /tmp/bazelisk
            fi

            sudo cp /tmp/bazelisk /usr/local/bin/bazel
            sudo chmod +x /usr/local/bin/bazel
      - run:
          name: Bazel test
          command: |
            bazel test --config=system-clang --repository_cache=./repo_cache ...
      - save_cache:
          key: bazel-darwin-bazelisk-{{ checksum ".bazelversion" }}
          paths:
            - /tmp/bazelisk
      - save_cache:
          key: bazel-darwin-repo-cache-{{ checksum "MODULE.bazel.lock" }}
          paths:
            - repo_cache
      - store_test_results:
          path: bazel-darwin-testlogs
workflows:
  build-and-test:
    jobs:
      - build-aarch64
      - build-bazel-aarch64
      - build-bazel-aarch64-darwin
