version: 2.1

executors:
  linux:
    docker:
      - image: cimg/base:2025.12
    resource_class: arm.medium
  darwin:
    macos:
      xcode: 16.4.0
    resource_class: m4pro.medium

jobs:
  build-bazel:
    parameters:
      os:
        type: executor
      config:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - run:
          name: Install Nix
          command: |
            curl --proto '=https' --tlsv1.2 -sSf -L https://install.lix.systems/lix | sh -s -- install --no-confirm
      - run:
          name: Bazel test
          command: |
            if [[ $(uname) = Linux ]]; then
                # Linux-in-Docker means the Lix daemon can only be used by root.
                sudo bash -c '. /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh && nix-shell --command "bazel test --config=<< parameters.config >> --config=san --repository_cache=./repo_cache //..."'
            else
              export __ETC_PROFILE_NIX_SOURCED= # TODO: ???
              . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

              # Sanitizers are not supported by GCC on Darwin.
              if [[ << parameters.config >> = gcc ]]; then
                  sanitizers=""
              else
                  sanitizers="--config=san"
              fi

              nix-shell --command "bazel test --config=<< parameters.config >> $sanitizers --repository_cache=./repo_cache //..."
            fi
      - store_test_results:
          path: bazel-testlogs
workflows:
  build-and-test:
    jobs:
      - build-bazel:
          matrix:
            parameters:
              os: [linux, darwin]
              config: [gcc, clang]
