version: 2.1

jobs:
  build-aarch64:
    docker:
      - image: cimg/base:2023.06
    resource_class: arm.medium
    steps:
      - run: |
          pip3 install meson
          sudo apt-get update
          sudo apt-get install ninja-build gcc-10 g++-10
      - checkout
      - run:
          name: "Configure"
          command: "CC=gcc-10 CXX=g++-10 ci/configure.sh build"
      - run:
          name: "Build"
          command: "ci/build.sh build"
      - run:
          name: "Test"
          command: "ci/test.sh build"
      - store_test_results:
          path: build/a3_gtest.xml
  build-m1:
    macos:
      xcode: 14.3.1
    resource_class: macos.m1.medium.gen1
    steps:
      - run: |
          pip3 install meson ninja
      - checkout
      - run:
          name: "Configure"
          command: "ci/configure.sh build"
      - run:
          name: "Build"
          command: "ci/build.sh build"
      - run:
          name: "Test"
          command: "ci/test.sh build"
      - store_test_results:
          path: build/a3_gtest.xml
workflows:
  build-and-test:
    jobs:
      - build-aarch64
      - build-m1
