load("//bazel:cc.bzl", "a3_cc_library")

package(default_visibility = ["//:__subpackages__"])

a3_cc_library(
    name = "platform",
    hdrs = [
        "alignof.h",
        "attribute.h",
        "cpp.h",
        "export.h",
        "platform.h",
    ],
)

a3_cc_library(
    name = "cpp",
    hdrs = ["cpp.h"],
)

a3_cc_library(
    name = "types",
    hdrs = ["types.h"],
    deps = [":platform"],
)

a3_cc_library(
    name = "socket_types",
    hdrs = ["socket_types.h"],
    deps = [":platform"],
)

a3_cc_library(
    name = "accept",
    srcs = glob(["accept/*.c"]),
    hdrs = ["accept.h"],
    deps = [
        ":platform",
        ":socket_types",
    ],
)

a3_cc_library(
    name = "aligned_alloc",
    srcs = glob(["aligned_alloc/*.c"]),
    hdrs = ["aligned_alloc.h"],
    deps = [":platform"],
)

a3_cc_library(
    name = "atomic",
    srcs = glob(["atomic/*.c"]),
    hdrs = ["atomic.h"] + glob(["atomic/*.h"]),
    deps = [":platform"],
)

a3_cc_library(
    name = "format",
    hdrs = ["format.h"],
    deps = [":platform"],
)

a3_cc_library(
    name = "likely",
    hdrs = ["likely.h"],
    deps = [":platform"],
)

a3_cc_library(
    name = "memmem",
    srcs = glob(["memmem/*.c"]),
    hdrs = ["memmem.h"],
    deps = [":platform"],
)

a3_cc_library(
    name = "strerror",
    srcs = glob(["strerror/*.c"]),
    hdrs = ["strerror.h"],
    deps = [":platform"],
)

a3_cc_library(
    name = "strncasecmp",
    srcs = glob(["strncasecmp/*.c"]),
    hdrs = ["strncasecmp.h"],
    deps = [":platform"],
)

a3_cc_library(
    name = "attributes",
    hdrs = ["attributes.h"],
    deps = [":platform"],
)
