load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "str",
    srcs = ["str.c"],
    hdrs = ["str.h"],
    deps = [
        "//a3/shim:attributes",
        "//a3/shim:memmem",
        "//a3/shim:platform",
        "//a3/shim:strncasecmp",
    ],
)

cc_library(
    name = "macro",
    hdrs = ["macro.h"],
)

cc_library(
    name = "try",
    hdrs = ["try.h"],
    deps = [
        ":macro",
        "//a3/shim:likely",
    ],
)

cc_library(
    name = "minmax",
    hdrs = ["minmax.h"],
)

cc_library(
    name = "buffer",
    srcs = ["buffer.c"],
    hdrs = ["buffer.h"],
    deps = [
        ":minmax",
        ":str",
        ":try",
        "//a3/shim:format",
        "//a3/shim:platform",
    ],
)

cc_library(
    name = "log",
    srcs = ["log.c"],
    hdrs = [
        "detail/log.h",
        "log.h",
        "panic.h",
    ],
    implementation_deps = ["//a3:str"],
    deps = [
        ":macro",
        "//a3/shim:attributes",
        "//a3/shim:format",
        "//a3/shim:likely",
        "//a3/shim:platform",
        "//a3/shim:strerror",
    ],
)

cc_library(
    name = "unwrap",
    hdrs = ["unwrap.h"],
    deps = [
        ":log",
        "//a3/shim:likely",
    ],
)

cc_library(
    name = "ht",
    hdrs = ["ht.h"],
    deps = [
        ":minmax",
        ":try",
        ":unwrap",
        "//a3/shim:platform",
        "//a3/shim:types",
        "//third_party/highwayhash",
    ],
)

cc_library(
    name = "cache",
    hdrs = ["cache.h"],
    deps = [
        ":ht",
        ":unwrap",
        "//a3/shim:platform",
        "//a3/shim:types",
    ],
)

cc_library(
    name = "pool",
    srcs = ["pool.c"],
    hdrs = ["pool.h"],
    deps = [
        ":unwrap",
        "//a3/shim:aligned_alloc",
        "//a3/shim:platform",
    ],
)

cc_library(
    name = "container_of",
    hdrs = ["container_of.h"],
)

cc_library(
    name = "ll",
    hdrs = ["ll.h"],
    deps = [
        ":container_of",
        ":macro",
        "//a3/shim:platform",
    ],
)

cc_library(
    name = "sll",
    hdrs = ["sll.h"],
    deps = [
        ":container_of",
        "//a3/shim:platform",
    ],
)

cc_library(
    name = "concepts",
    hdrs = glob(["concepts/*.hh"]),
)

cc_library(
    name = "base",
    hdrs = ["fwd.hh"],
)

cc_library(
    name = "nonnull",
    hdrs = ["nonnull.hh"],
    deps = [
        ":base",
        ":concepts",
        ":log",
    ],
)

cc_library(
    name = "pin",
    hdrs = ["pin.hh"],
)

cc_library(
    name = "rc",
    hdrs = [
        "rc.h",
        "rc.hh",
    ],
    deps = [":pin"],
)

cc_library(
    name = "vec",
    srcs = ["vec.c"],
    hdrs = ["vec.h"],
    deps = [
        ":macro",
        ":unwrap",
        "//a3/shim:aligned_alloc",
        "//a3/shim:platform",
    ],
)
