load("//bazel:cc.bzl", "a3_cc_test")

a3_cc_test(
    name = "accept",
    size = "small",
    srcs = ["accept.cc"],
    deps = [
        "//a3:unwrap",
        "//a3/shim:accept",
        "//a3/shim:platform",
        "//a3/shim:socket_types",
        "@googletest//:gtest_main",
    ],
)

a3_cc_test(
    name = "memmem",
    size = "small",
    srcs = ["memmem.cc"],
    deps = [
        "//a3/shim:memmem",
        "@googletest//:gtest_main",
    ],
)
