load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_test(
    name = "accept",
    size = "small",
    srcs = ["accept.cc"],
    deps = [
        "//a3/shim:accept",
        "//a3/shim:platform",
        "//a3/shim:socket_types",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "memmem",
    size = "small",
    srcs = ["memmem.cc"],
    deps = [
        "//a3/shim:memmem",
        "@googletest//:gtest_main",
    ],
)
