name: Build and test

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.c'
      - '**/*.h'
      - '**/*.cc'
      - '**/*.hh'
      - '.github/workflows/build.yml'
      - '**/meson.build'
      - 'extern/liba3'
      - 'boilerplate'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            c_compiler: gcc-10
            cxx_compiler: g++-10
          - os: windows-latest
            c_compiler: cl
            cxx_compiler: cl

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - uses: ilammy/msvc-dev-cmd@v1
      if: runner.os == 'Windows'

    - name: Install dependencies.
      run: pip install meson ninja

    - name: Configure
      if: runner.os != 'Windows'
      env:
        CC: ${{ matrix.c_compiler }}
        CXX: ${{ matrix.cxx_compiler }}
      run: meson setup --buildtype debug --werror -Db_sanitize=address,undefined -Dcpp_std=c++20 build

    - name: Configure (Windows)
      if: runner.os == 'Windows'
      env:
        CC: ${{ matrix.c_compiler }}
        CXX: ${{ matrix.cxx_compiler }}
      # NOTE: ASAN temporarily disabled for Windows builds due to mysterious error on test teardown.
      run: meson setup --buildtype debug --werror  -Dcpp_std=c++20 build

    - name: Build
      run: meson compile -C build

    - name: Test
      id: test
      run: meson test -C build

    - name: Upload failed test logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: Test logs
        path: build/meson-logs/testlog.txt
