name: Build and test

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.c'
      - '**/*.h'
      - '**/*.cc'
      - '**/*.hh'
      - '.github/workflows/build.yml'
      - '**/meson.build'
      - 'extern/liba3'
      - 'boilerplate'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        architecture: [amd64, s390x, arm, ppc]
        include:
          - os: windows-latest
            c_compiler: cl
            cxx_compiler: cl
          - os: ubuntu-latest
            architecture: amd64
            c_compiler: gcc-10
            cxx_compiler: g++-10
        exclude:
          - os: windows-latest
            architecture: s390x
          - os: macos-latest
            architecture: s390x
          - os: windows-latest
            architecture: arm
          - os: macos-latest
            architecture: arm
          - os: windows-latest
            architecture: ppc
          - os: macos-latest
            architecture: ppc

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - uses: ilammy/msvc-dev-cmd@v1
      if: runner.os == 'Windows'

    - name: Install dependencies.
      run: pip install meson ninja

    - name: Fixup cross triple quirks.
      if: matrix.os == 'ubuntu-latest' && matrix.architecture != 'amd64' && matrix.architecture != 'ppc' && matrix.architecture != 'arm'
      run: |
        echo "DEB_ARCH=${{ matrix.architecture }}" >> $GITHUB_ENV
        echo "CROSS_TRIPLE=${{ matrix.architecture }}-linux-gnu" >> $GITHUB_ENV

    - name: Fixup cross triple quirks.
      if: matrix.os == 'ubuntu-latest' && matrix.architecture == 'arm'
      run: |
        echo "DEB_ARCH=armel" >> $GITHUB_ENV
        echo "CROSS_TRIPLE=arm-linux-gnueabi" >> $GITHUB_ENV

    - name: Fixup cross triple quirks.
      if: matrix.os == 'ubuntu-latest' && matrix.architecture == 'ppc'
      run: |
        echo "DEB_ARCH=powerpc" >> $GITHUB_ENV
        echo "CROSS_TRIPLE=powerpc-linux-gnu" >> $GITHUB_ENV

    - name: Set up cross toolchain and emulator.
      if: matrix.os == 'ubuntu-latest' && matrix.architecture != 'amd64'
      run: |
        sudo apt-get update
        sudo apt-get install -y dpkg-dev qemu-user meson gcc-$CROSS_TRIPLE g++-$CROSS_TRIPLE pkg-config-$CROSS_TRIPLE
        sudo mkdir /etc/qemu-binfmt
        sudo ln -s /usr/$CROSS_TRIPLE /etc/qemu-binfmt/${{ matrix.architecture }}
        /usr/share/meson/debcrossgen --arch $DEB_ARCH -o ${{ matrix.architecture }}.ini
        sed -i "/^\[binaries\]/a exe_wrapper = 'qemu-${{ matrix.architecture }}'" ${{ matrix.architecture }}.ini
        sudo apt-get remove -y meson
        echo "MESON_CROSS_ARG=--cross-file ${{ matrix.architecture }}.ini" >> $GITHUB_ENV

    - name: Enable sanitizers.
      # NOTE: ASAN temporarily disabled for Windows builds due to mysterious error on test teardown.
      if: runner.os != 'Windows' && matrix.architecture == 'amd64'
      run: echo "MESON_SAN_ARG=-Db_sanitize=address,undefined" >> $GITHUB_ENV

    - name: Configure.
      env:
        CC: ${{ matrix.c_compiler }}
        CXX: ${{ matrix.cxx_compiler }}
      run: meson setup $MESON_CROSS_ARG $MESON_SAN_ARG --buildtype debug --werror -Dcpp_std=c++20 build

    - name: Build.
      run: meson compile -C build

    - name: Test.
      id: test
      run: meson test -C build

    - name: Upload failed logs.
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: Test logs
        path: build/meson-logs/
