name: Build and test

on:
  push:
    paths:
      - '**/*.c'
      - '**/*.h'
      - '**/*.cc'
      - '**/*.hh'
      - '.github/workflows/build.yml'
      - 'CMakeLists.txt'
      - 'extern/liba3'
      - 'boilerplate'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            c_compiler: gcc-9
            cxx_compiler: g++-9

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install Meson.
      run: pip install meson ninja

    - name: Configure
      shell: bash
      env:
        CC: ${{ matrix.c_compiler }}
        CXX: ${{ matrix.cxx_compiler }}
      run: meson setup --buildtype release --werror build

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: meson compile

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: meson test
