name: Build and test

on:
  push:
    paths:
      - '**/*.c'
      - '**/*.h'
      - '**/*.cc'
      - '**/*.hh'
      - '.github/workflows/build.yml'
      - '**/meson.build'
      - 'extern/liba3'
      - 'boilerplate'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            c_compiler: gcc-9
            cxx_compiler: g++-9
          - os: windows-latest
            c_compiler: cl
            cxx_compiler: cl

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - uses: ilammy/msvc-dev-cmd@v1
      if: runner.os == 'Windows'

    - name: Install dependencies.
      run: pip install meson ninja

    - name: Configure
      env:
        CC: ${{ matrix.c_compiler }}
        CXX: ${{ matrix.cxx_compiler }}
      run: meson setup --buildtype release --werror build

    - name: Build
      run: meson compile -C build

    - name: Test
      run: meson test -C build
