name: Build and test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            c_compiler: gcc-9
            cxx_compiler: g++-9

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Create build directory
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure
      working-directory: ${{runner.workspace}}/build
      shell: bash
      env:
        CC: ${{ matrix.c_compiler }}
        CXX: ${{ matrix.cxx_compiler }}
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build .

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: ctest
