name: Build and test with Nix

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.c'
      - '**/*.h'
      - '**/*.cc'
      - '**/*.hh'
      - '.github/workflows/nix.yml'
      - '**/meson.build'
      - 'boilerplate'
      - '**/*.nix'
      - 'flake.lock'

jobs:
  build-nix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [release, clang/release, clang/debug, libcxxClang/release, mingw/release]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: DeterminateSystems/nix-installer-action@v9 # Locally revert to v8 if running with act.
      - uses: DeterminateSystems/magic-nix-cache-action@v3
      - name: Build with Nix
        run: nix build ".#a3/${{ matrix.target }}"
