name: Update flake.lock
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v1
      - uses: DeterminateSystems/update-flake-lock@v19
        with:
          pr-title: "Update flake.lock"
          pr-labels: |
            dependencies
            automatic
